name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    - name: Configure AWS credentials
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} > ~/.aws/credentials
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials
      env:
        AWS_REGION: us-east-1  # Modify as needed

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -out=terraform.tfplan
      
    - name: Terraform Apply
      run: terraform apply -input=false terraform.tfplan
      continue-on-error: true  # To prevent a failed plan from failing the entire workflow

    - name: Upload State File to S3
      run: |
        aws s3 cp terraform.tfstate s3://your-s3-bucket-name/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
