name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

      env:
        AWS_REGION: us-east-1

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: |
        terraform init
        terraform plan -out=terraform.tfplan \
          -var "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "AWS_REGION=${{ secrets.AWS_REGION }}" \
          -var "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      working-directory: CI-CD-Terraform-Github-Action/main.tf
      
    - name: Terraform Apply
      run: terraform apply -input=false terraform.tfplan
      continue-on-error: true  # To prevent a failed plan from failing the entire workflow

    - name: Upload State File to S3
      run: |
        aws s3 cp terraform.tfstate s3://your-s3-bucket-name/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
